project:
  type: website
  output-dir: docs

website:
  title: "Kat Le"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: home
      - href: blog.qmd
        text: blog
  page-footer:
    background: light
    right: This website is built with {{< fa brands github title= "github icon" >}} Github.

format:
  html:
    theme: 
      light: lux
      dark: lux
    toc: false
    page-layout: full
    #mainfont: Montserrat

editor: visual

