project:
  type: website
  output-dir: docs

website:
  navbar:
    favion: images/Kat_Le.jpg # supposed to give you a logo in the tab
    title: "waaazzzzaaaa"
    logo: images/Kat_Le.jpg # replace w logo
    logo-alt: "alt text here"
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: resources.qmd
        text: resources
      - href: resume/KatherineLe_Resume_Jan2022.pdf
        text: resume
    right: 
      - icon: github
        href: https://github.com/katleyq
  page-footer: 
    background: light
    left: 
    - "Copyright 2023, Kat Le"
    right:
    - icon: github 
      href: https://github.com/katleyq

format:
  html:
    theme: styles.scss 
    mainfont: Montserrat
    toc: false
    page-layout: full

editor: visual

