project:
  type: website
  output-dir: docs

website:
  title: "waaazzzzaaaa"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: resources.qmd
        text: resources

format:
  html:
    theme: 
      light: lux
      dark: lux
    css: styles.css
    toc: false
    page-layout: full

editor: visual

