project:
  type: website
  output-dir: docs

website:
  title: "waaazzzzaaaa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual

