project:
  type: website
  output-dir: docs

website:
  title: "Kat Le"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about me
      - href: blog.qmd
        text: blog
  page-footer:
    background: $color1
    right: This website is built with {{< fa brands github title= "github icon" >}} Github.

format:
  html:
    theme: 
      light: [lux, styles.scss]
      dark: [lux, styles.scss]
    toc: false
    page-layout: full

editor: visual

